name: CI Pipeline

# Запускаємо пайплайн при кожному пуші в main та при створенні Pull Request
on:
  push:
    branches:[ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Завантажуємо наш код на сервер GitHub
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Встановлюємо Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip' # Кешуємо залежності для швидкості

    # 3. Встановлюємо наші інструменти для розробки
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    # 4. Перевіряємо форматування коду (Black)
    - name: Check formatting with Black
      run: black . --check

    # 5. Шукаємо логічні помилки та зайві імпорти (Ruff)
    - name: Lint with Ruff
      run: ruff check .